version: '3'

services:

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports: 
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d